#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

const args = process.argv.slice(2);
const inputFile = args[0];

function getFlag(flag, defaultVal) {
  const idx = args.indexOf(flag);
  if (idx === -1) return defaultVal;
  return args[idx + 1];
}

if (!inputFile) {
  console.log(`
Usage:
  node generate_report.js analysis.json [options]

Options:
  --output <file>      Output HTML filename (default: report.html)
  --lang <en|ko>       Language (default: en)
  --linkedin <url>     LinkedIn profile URL for footer CTA
`);
  process.exit(1);
}

const outputFile = getFlag('--output', 'report.html');
const lang = getFlag('--lang', 'en');
const linkedinUrl = getFlag('--linkedin', null);
const waitlistUrl = getFlag('--waitlist', null);

const analysis = JSON.parse(fs.readFileSync(path.resolve(inputFile), 'utf-8'));

function esc(str) {
  return (str || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

// --- i18n ---
const i18n = {
  en: {
    introLine: (name, n) => `We read <span class="num" data-target="${n}">0</span> reviews of ${esc(name)}.`,
    signalLine: (rate, n) => `Of those, <span class="accent">${rate}%</span> contained churn signals — <span class="accent">${n}</span> reviews where users told us exactly why they're leaving.`,
    dotCaption: 'Each dot is one review. The red ones are churn signals.',
    patternLine: (n) => `We classified those signals into <span class="accent">${n}</span> patterns.`,
    patternHint: 'Click a bar to read the actual reviews.',
    deepdiveIntro: "Here's what we found when we dug into the top 3.",
    issueNum: (n) => `Issue #${n}`,
    mentions: 'mentions',
    severity: 'Severity',
    journeyStage: 'Journey Stage',
    rootCause: 'Why this happens',
    compounding: 'How it compounds',
    whatToDo: 'What to do about it',
    quickWin: 'Quick win',
    mediumTerm: 'Medium-term',
    longTerm: 'Long-term',
    testThis: 'Test this',
    experimentsTitle: 'Experiment Roadmap',
    experimentsIntro: 'Four experiments to validate the hypotheses above — ordered by priority.',
    expHypothesis: 'Hypothesis',
    expDesign: 'Test Design',
    expMetric: 'Primary Metric',
    expGuardrail: 'Guardrail',
    expDuration: 'Duration',
    expSample: 'Sample Size',
    expExpected: 'Expected Outcome',
    expPrereq: 'Prerequisite',
    ctaTitle: 'The most expensive question this report can\'t answer',
    ctaLine1: (top1) => `Now you know the top churn drivers — <strong>${top1}</strong> and two more. You have a clear list of what to fix and where in the funnel users break off.`,
    ctaLine2: 'But none of this tells you the one thing that\'s actually burning money right now: <strong>is the ad spend you\'re running actually turning into subscribers?</strong>',
    ctaLine3: 'If you\'re being honest, you probably know the answer looks something like this: subscription numbers in RevenueCat, CPI calculations in a Google Sheet, and everything in between is a gut feeling.',
    ctaLine4: 'The churn issues above become 10x more urgent once you realize you can\'t see the full picture — from ad click to trial start to subscription renewal — in one place. You\'re fixing leaks in a funnel you can\'t actually see end-to-end.',
    ctaLine5: (brand) => `<strong>${brand}</strong> answers one question: <em>"Is my Paid UA driving subscriptions?"</em> One funnel, from ad click to renewal, across Meta, Google, TikTok, and Apple Search Ads. Self-serve setup in under an hour, starting at $0/mo.`,
    ctaLink: 'Learn more about Core Plan',
    waitlistTitle: 'Early access offer',
    waitlistLine1: 'Core Plan is launching soon. Join the waitlist today, and you\'ll start with <strong>90,000 Attributed Installs free</strong> over your first 3 months.',
    waitlistLine2: 'For context: the standard free tier covers 15,000 installs per year. This is <strong>6x that</strong>, concentrated into your first 90 days — enough to measure every paid install your app gets, at zero cost.',
    waitlistLine3: 'This offer is only available to early access signups.',
    waitlistBtn: 'Join the waitlist',
    linkedinLine: 'Want to discuss this analysis further?',
    linkedinCta: "Let's connect on LinkedIn",
    methodologyTitle: 'How we analyzed the data',
    footer: 'Generated by Subscription Churn Diagnosis Skill · Powered by Claude Code',
    dd1Punch: (name) => `When the core feature fails, the app's reason to exist disappears.`,
    dd2Title: 'The user journey breaks here',
    dd2Steps: ['See ad', 'Download', 'Sign up', 'Paywall', '???'],
    dd3Expect: 'What users expected',
    dd3Got: 'What users experienced',
  },
  ko: {
    introLine: (name, n) => `${esc(name)}의 리뷰 <span class="num" data-target="${n}">0</span>개를 읽었습니다.`,
    signalLine: (rate, n) => `그 중 <span class="accent">${rate}%</span>에서 이탈 신호가 나왔습니다 — 사용자가 왜 떠나는지 직접 말해준 리뷰 <span class="accent">${n}</span>건.`,
    dotCaption: '각 점은 리뷰 1건입니다. 빨간 점이 이탈 신호입니다.',
    patternLine: (n) => `이탈 신호를 분류하니 <span class="accent">${n}</span>가지 패턴이 보였습니다.`,
    patternHint: '바를 클릭하면 실제 리뷰를 볼 수 있습니다.',
    deepdiveIntro: '상위 3개 이슈를 파고들었습니다.',
    issueNum: (n) => `이슈 #${n}`,
    mentions: '건',
    severity: '심각도',
    journeyStage: '여정 단계',
    rootCause: '왜 이런 일이 생기는가',
    compounding: '어떻게 악화되는가',
    whatToDo: '무엇을 해야 하는가',
    quickWin: '빠른 개선',
    mediumTerm: '중기 과제',
    longTerm: '장기 과제',
    testThis: '이 가설을 테스트하세요',
    experimentsTitle: '실험 로드맵',
    experimentsIntro: '위 가설들을 검증하기 위한 실험입니다 — 우선순위 순으로 정렬.',
    expHypothesis: '가설',
    expDesign: '실험 설계',
    expMetric: '핵심 지표',
    expGuardrail: '가드레일',
    expDuration: '기간',
    expSample: '표본 크기',
    expExpected: '기대 결과',
    expPrereq: '선행 조건',
    ctaTitle: '이 리포트가 답하지 못하는, 가장 비싼 질문',
    ctaLine1: (top1) => `이제 핵심 이탈 원인을 알았습니다 — <strong>${top1}</strong> 외 2가지. 무엇을 고쳐야 하고, 퍼널 어디서 이탈하는지도 파악했습니다.`,
    ctaLine2: '하지만 이 중 어떤 것도, 지금 돈이 타고 있는 진짜 질문에는 답하지 못합니다: <strong>내가 쓰고 있는 광고비가 실제로 구독으로 이어지고 있는 건가?</strong>',
    ctaLine3: '솔직히, 지금 이 질문에 대한 답은 이렇게 생겼을 겁니다 — 구독 숫자는 RevenueCat에서, CPI 계산은 Google Sheets에서, 그 사이는 전부 감.',
    ctaLine4: '위에서 분석한 이탈 이슈들은, 광고 클릭부터 트라이얼 시작, 구독 갱신까지의 전체 퍼널을 한 곳에서 볼 수 없다는 걸 깨닫는 순간 10배 더 긴급해집니다. 끝에서 끝까지 보이지 않는 퍼널의 구멍을 막고 있는 셈이니까요.',
    ctaLine5: (brand) => `<strong>${brand}</strong>은 하나의 질문에 답합니다: <em>"내 Paid UA가 구독을 만들고 있는가?"</em> 광고 클릭부터 구독 갱신까지, Meta·Google·TikTok·Apple Search Ads를 하나의 퍼널로. 1시간 내 셀프서브 설정, $0/월부터.`,
    ctaLink: 'Core Plan 자세히 보기',
    waitlistTitle: '얼리 액세스 오퍼',
    waitlistLine1: 'Core Plan이 곧 런칭됩니다. 지금 웨이팅리스트에 등록하시면, 첫 3개월간 <strong>90,000 Attributed Installs를 무료</strong>로 제공합니다.',
    waitlistLine2: '참고로, 일반 무료 티어는 연간 15,000건입니다. 이건 그 <strong>6배</strong>를 첫 90일에 집중 제공하는 것 — 앱의 유료 설치를 전부 측정하기에 충분한 양입니다.',
    waitlistLine3: '이 오퍼는 얼리 액세스 등록자에게만 제공됩니다.',
    waitlistBtn: '웨이팅리스트 등록하기',
    linkedinLine: '이 분석에 대해 더 이야기하고 싶으신가요?',
    linkedinCta: 'LinkedIn에서 대화해요',
    methodologyTitle: '분석 방법론',
    footer: 'Subscription Churn Diagnosis Skill로 생성 · Powered by Claude Code',
    dd1Punch: (name) => `핵심 기능이 작동하지 않으면, 앱의 존재 이유가 사라집니다.`,
    dd2Title: '사용자 여정이 여기서 끊깁니다',
    dd2Steps: ['광고 클릭', '다운로드', '이메일 입력', '페이월', '???'],
    dd3Expect: '사용자가 기대한 것',
    dd3Got: '사용자가 경험한 것',
  }
};
const t = i18n[lang] || i18n.en;

// --- Data Processing ---
const sorted = [...analysis.categories].sort((a, b) => b.score - a.score);
const top3 = sorted.slice(0, 3);
const maxScore = Math.max(...sorted.map(c => c.score));
const signalRate = analysis.totalReviews > 0 ? Math.round(analysis.subscriptionRelated / analysis.totalReviews * 100) : 0;
const barW = (score) => Math.max(8, Math.round((score / maxScore) * 100));

// Highlight churn-related keywords in quotes
function highlightQuote(text) {
  let h = esc(text);
  const patterns = [
    /\b(error|errors|crash|crashes|buggy|broken|doesn&#39;t work|never goes on|never|fail|failed|sketchy)\b/gi,
    /\b(pay|charged?|trial|subscribe|force|forced|commit|money|scam)\b/gi,
    /\b(not as good|doesn&#39;t help|no option|expected|can&#39;t|won&#39;t)\b/gi,
  ];
  patterns.forEach(p => { h = h.replace(p, '<mark>$&</mark>'); });
  return h;
}

// Deterministic dot positions for signal dots
function dotGrid() {
  const total = analysis.totalReviews;
  const signals = analysis.subscriptionRelated;
  if (total === 0) return '';
  const positions = new Set();
  for (let i = 0; i < signals; i++) {
    positions.add(Math.round((i + 0.5) * total / signals));
  }
  const dots = [];
  for (let i = 0; i < total; i++) {
    dots.push(`<span class="dot${positions.has(i) ? ' signal' : ''}"></span>`);
  }
  return dots.join('');
}

// --- Methodology (collapsible) ---
function methodologyHTML() {
  const m = analysis.methodology;
  if (!m) {
    // Generate default methodology
    return `
    <details class="methodology">
      <summary>${t.methodologyTitle}</summary>
      <div class="methodology-body">
        <ol>
          <li>Scraped reviews from App Store (iOS) and Google Play Store (US market).</li>
          <li>Collected ${analysis.totalReviews} reviews across both platforms.</li>
          <li>Classified each review into 8 predefined churn signal categories.</li>
          <li>Assigned severity scores (1–5) to each category.</li>
          <li>Calculated weighted score = mentions × severity.</li>
          <li>Performed root cause analysis on the top 3 categories by score.</li>
        </ol>
      </div>
    </details>`;
  }
  return `
  <details class="methodology">
    <summary>${esc(m.title || t.methodologyTitle)}</summary>
    <div class="methodology-body">
      <p>${esc(m.description)}</p>
      <ol>
        ${m.steps.map(s => `<li><strong>${esc(s.label)}</strong> — ${esc(s.detail)}</li>`).join('\n        ')}
      </ol>
    </div>
  </details>`;
}

// --- Bar Chart ---
function barChart() {
  return sorted.map((cat, i) => {
    const isTop3 = i < 3;
    const quotesHtml = (cat.quotes || []).map(q =>
      `<div class="bar-quote">"${highlightQuote(q)}"</div>`
    ).join('');
    return `
    <div class="bar-row${isTop3 ? ' top3' : ''}" onclick="toggleQuotes(this)">
      <div class="bar-label-row">
        <span class="bar-name">${esc(cat.name)}</span>
        <span class="bar-meta">${cat.count} ${t.mentions} · ${t.severity} ${cat.severity}/5</span>
      </div>
      <div class="bar-track">
        <div class="bar-fill" style="width:${barW(cat.score)}%"><span class="bar-score">${cat.score}</span></div>
      </div>
    </div>
    <div class="bar-quotes-panel" style="display:none">${quotesHtml}</div>`;
  }).join('');
}

// --- Deep Dive #1: Big Quotes Layout ---
function deepDive1(cat, idx) {
  return `
  <section class="section deepdive">
    <div class="dd-label">${t.issueNum(idx + 1)}</div>
    <h2 class="dd-title">${esc(cat.name)}</h2>
    <div class="dd-meta">${cat.count} ${t.mentions} · ${t.severity} ${cat.severity}/5 · ${t.journeyStage}: ${esc(cat.journeyStage)}</div>

    <div class="dd1-quotes">
      ${(cat.quotes || []).map(q => `
      <blockquote class="big-quote">"${highlightQuote(q)}"</blockquote>`).join('')}
    </div>

    <p class="dd-punchline">${t.dd1Punch(cat.name)}</p>

    <div class="dd-analysis">
      <h3>${t.rootCause}</h3>
      <p>${esc(cat.rootCause)}</p>
    </div>
    <div class="dd-analysis">
      <h3>${t.compounding}</h3>
      <p>${esc(cat.compounding)}</p>
    </div>

    ${actionsBlock(cat)}
  </section>`;
}

// --- Deep Dive #2: Journey Timeline Layout ---
function deepDive2(cat, idx) {
  const steps = t.dd2Steps;
  return `
  <section class="section deepdive">
    <div class="dd-label">${t.issueNum(idx + 1)}</div>
    <h2 class="dd-title">${esc(cat.name)}</h2>
    <div class="dd-meta">${cat.count} ${t.mentions} · ${t.severity} ${cat.severity}/5 · ${t.journeyStage}: ${esc(cat.journeyStage)}</div>

    <p class="dd-subtitle">${t.dd2Title}</p>
    <div class="journey">
      ${steps.map((s, i) => {
        const isBreak = i === steps.length - 2;
        const isFaded = i === steps.length - 1;
        return `<div class="journey-step${isBreak ? ' break' : ''}${isFaded ? ' faded' : ''}">
          <div class="journey-dot"></div>
          <span>${esc(s)}</span>
        </div>${i < steps.length - 1 ? '<div class="journey-line' + (isFaded ? ' faded' : '') + '"></div>' : ''}`;
      }).join('')}
    </div>

    <div class="dd2-quotes">
      ${(cat.quotes || []).map(q => `
      <div class="speech-bubble">"${highlightQuote(q)}"</div>`).join('')}
    </div>

    <div class="dd-analysis">
      <h3>${t.rootCause}</h3>
      <p>${esc(cat.rootCause)}</p>
    </div>
    <div class="dd-analysis">
      <h3>${t.compounding}</h3>
      <p>${esc(cat.compounding)}</p>
    </div>

    ${actionsBlock(cat)}
  </section>`;
}

// --- Deep Dive #3: Before/After Layout ---
function deepDive3(cat, idx) {
  return `
  <section class="section deepdive">
    <div class="dd-label">${t.issueNum(idx + 1)}</div>
    <h2 class="dd-title">${esc(cat.name)}</h2>
    <div class="dd-meta">${cat.count} ${t.mentions} · ${t.severity} ${cat.severity}/5 · ${t.journeyStage}: ${esc(cat.journeyStage)}</div>

    <div class="comparison">
      <div class="comp-col expect">
        <h4>${t.dd3Expect}</h4>
        <p>${esc(cat.rootCause.split('—')[0].split('–')[0].trim())}</p>
      </div>
      <div class="comp-divider"></div>
      <div class="comp-col got">
        <h4>${t.dd3Got}</h4>
        ${(cat.quotes || []).map(q => `
        <blockquote>"${highlightQuote(q)}"</blockquote>`).join('')}
      </div>
    </div>

    <div class="dd-analysis">
      <h3>${t.rootCause}</h3>
      <p>${esc(cat.rootCause)}</p>
    </div>
    <div class="dd-analysis">
      <h3>${t.compounding}</h3>
      <p>${esc(cat.compounding)}</p>
    </div>

    ${actionsBlock(cat)}
  </section>`;
}

// --- Actions Block (shared) ---
function actionsBlock(cat) {
  if (!cat.actions) return '';
  const levels = [
    { key: 'quick', label: t.quickWin },
    { key: 'medium', label: t.mediumTerm },
    { key: 'major', label: t.longTerm },
  ];
  return `
    <div class="dd-actions">
      <h3>${t.whatToDo}</h3>
      ${levels.filter(l => cat.actions[l.key]).map(l => `
      <div class="action-row">
        <span class="action-level">${l.label}</span>
        <span class="action-text">${esc(cat.actions[l.key])}</span>
      </div>`).join('')}
    </div>
    ${cat.testHypothesis ? `
    <div class="dd-test">
      <strong>${t.testThis}:</strong> ${esc(cat.testHypothesis)}
    </div>` : ''}`;
}

// --- Experiments ---
function experimentsHTML() {
  if (!analysis.experiments?.length) return '';
  const hasDetail = analysis.experiments[0].design;

  if (hasDetail) {
    return `
    <section class="section">
      <h2 class="section-title">${t.experimentsTitle}</h2>
      <p class="section-intro">${t.experimentsIntro}</p>
      <div class="exp-cards">
        ${analysis.experiments.map(exp => `
        <div class="exp-card">
          <div class="exp-header">
            ${exp.priority ? `<span class="exp-priority">${esc(exp.priority)}</span>` : ''}
            <p class="exp-hypothesis">"${esc(exp.hypothesis)}"</p>
          </div>
          <div class="exp-body">
            <div class="exp-field">
              <span class="exp-label">${t.expDesign}</span>
              <p>${esc(exp.design)}</p>
            </div>
            <div class="exp-grid">
              <div class="exp-field">
                <span class="exp-label">${t.expMetric}</span>
                <p>${esc(exp.metric)}</p>
              </div>
              ${exp.guardrail ? `<div class="exp-field">
                <span class="exp-label">${t.expGuardrail}</span>
                <p>${esc(exp.guardrail)}</p>
              </div>` : ''}
              <div class="exp-field">
                <span class="exp-label">${t.expDuration}</span>
                <p>${esc(exp.duration || '')}</p>
              </div>
              ${exp.sampleSize ? `<div class="exp-field">
                <span class="exp-label">${t.expSample}</span>
                <p>${esc(exp.sampleSize)}</p>
              </div>` : ''}
            </div>
            <div class="exp-field expected">
              <span class="exp-label">${t.expExpected}</span>
              <p>${esc(exp.expected)}</p>
            </div>
            ${exp.prerequisite ? `<div class="exp-field prereq">
              <span class="exp-label">${t.expPrereq}</span>
              <p>${esc(exp.prerequisite)}</p>
            </div>` : ''}
          </div>
        </div>`).join('')}
      </div>
    </section>`;
  }

  // Fallback: simple table for old-format experiments
  return `
  <section class="section">
    <h2 class="section-title">${t.experimentsTitle}</h2>
    <table class="exp-table">
      <thead><tr><th>${t.expHypothesis}</th><th>${t.expDesign}</th><th>${t.expExpected}</th></tr></thead>
      <tbody>${analysis.experiments.map(exp => `
        <tr><td>${esc(exp.hypothesis)}</td><td>${esc(exp.test || exp.design || '')}</td><td>${esc(exp.expected)}</td></tr>`).join('')}
      </tbody>
    </table>
  </section>`;
}

// --- CTA ---
function ctaHTML() {
  const top1Name = top3[0]?.name || '';
  const waitlistBlock = waitlistUrl ? `
    <div class="waitlist-box">
      <div class="waitlist-label">${t.waitlistTitle}</div>
      <p>${t.waitlistLine1}</p>
      <p>${t.waitlistLine2}</p>
      <p class="waitlist-fine">${t.waitlistLine3}</p>
      <a href="${esc(waitlistUrl)}" target="_blank" class="waitlist-btn">${t.waitlistBtn} &rarr;</a>
    </div>` : `<a href="https://airbridge.io" target="_blank" class="cta-link">${t.ctaLink} &rarr;</a>`;

  return `
  <section class="section cta-section">
    <h2 class="cta-title">${t.ctaTitle}</h2>
    <p>${t.ctaLine1(top1Name)}</p>
    <p>${t.ctaLine2}</p>
    <p>${t.ctaLine3}</p>
    <p>${t.ctaLine4}</p>
    <p class="cta-closer">${t.ctaLine5('Airbridge Core Plan')}</p>
    ${waitlistBlock}
  </section>`;
}

// --- LinkedIn ---
function linkedinHTML() {
  if (!linkedinUrl) return '';
  return `
  <section class="section connect-section">
    <p>${t.linkedinLine}</p>
    <a href="${esc(linkedinUrl)}" target="_blank" class="linkedin-link">${t.linkedinCta} &rarr;</a>
  </section>`;
}

// =====================
// === HTML Assembly ===
// =====================

const html = `<!DOCTYPE html>
<html lang="${lang}">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Churn Diagnosis — ${esc(analysis.app.name)}</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
<style>
  :root {
    --bg: #FAFAF9;
    --text: #1C1917;
    --text-2: #78716C;
    --text-3: #A8A29E;
    --border: #D6D3D1;
    --accent: #DC2626;
    --accent-light: #FEF2F2;
    --surface: #FFFFFF;
    --max-w: 680px;
  }

  * { margin: 0; padding: 0; box-sizing: border-box; }

  body {
    font-family: 'Inter', system-ui, -apple-system, sans-serif;
    background: var(--bg);
    color: var(--text);
    line-height: 1.7;
    -webkit-font-smoothing: antialiased;
  }

  @media (prefers-reduced-motion: reduce) {
    * { animation: none !important; transition: none !important; }
  }

  /* ---- Sections ---- */
  .section { max-width: var(--max-w); margin: 0 auto; padding: 0 24px; }
  .section + .section { margin-top: 100px; }
  .section-title {
    font-size: 20px;
    font-weight: 700;
    letter-spacing: -0.02em;
    margin-bottom: 8px;
  }
  .section-intro {
    color: var(--text-2);
    font-size: 15px;
    margin-bottom: 32px;
  }

  /* ---- Intro ---- */
  .intro {
    max-width: var(--max-w);
    margin: 0 auto;
    padding: 120px 24px 0;
  }
  .intro h1 {
    font-size: 36px;
    font-weight: 700;
    line-height: 1.3;
    letter-spacing: -0.03em;
  }
  .intro .num {
    color: var(--accent);
    font-variant-numeric: tabular-nums;
  }
  .intro .app-meta {
    margin-top: 12px;
    font-size: 14px;
    color: var(--text-3);
  }
  .intro .summary {
    margin-top: 28px;
    font-size: 16px;
    line-height: 1.8;
    color: var(--text-2);
    max-width: 600px;
  }

  /* ---- Methodology (collapsible) ---- */
  .methodology {
    margin-top: 32px;
    border: 1px solid var(--border);
    border-radius: 8px;
    overflow: hidden;
  }
  .methodology summary {
    padding: 14px 20px;
    font-size: 13px;
    font-weight: 600;
    color: var(--text-2);
    cursor: pointer;
    list-style: none;
    display: flex;
    align-items: center;
    gap: 8px;
  }
  .methodology summary::-webkit-details-marker { display: none; }
  .methodology summary::before {
    content: '+';
    font-size: 16px;
    font-weight: 400;
    color: var(--text-3);
    width: 20px;
    text-align: center;
    transition: transform 200ms;
  }
  .methodology[open] summary::before {
    content: '−';
  }
  .methodology-body {
    padding: 0 20px 20px;
    font-size: 13px;
    color: var(--text-2);
    line-height: 1.7;
  }
  .methodology-body p { margin-bottom: 12px; }
  .methodology-body ol {
    padding-left: 20px;
    display: flex;
    flex-direction: column;
    gap: 8px;
  }
  .methodology-body li { padding-left: 4px; }
  .methodology-body strong { color: var(--text); font-weight: 600; }

  /* ---- Dot Grid ---- */
  .dot-section {
    max-width: var(--max-w);
    margin: 100px auto 0;
    padding: 0 24px;
  }
  .dot-section .lead {
    font-size: 24px;
    font-weight: 600;
    letter-spacing: -0.02em;
    line-height: 1.5;
    margin-bottom: 28px;
  }
  .dot-section .lead .accent { color: var(--accent); font-weight: 700; }
  .dot-grid {
    display: flex;
    flex-wrap: wrap;
    gap: 5px;
    margin-bottom: 12px;
  }
  .dot {
    width: 10px;
    height: 10px;
    border-radius: 50%;
    background: var(--border);
    transition: transform 150ms;
  }
  .dot.signal { background: var(--accent); }
  .dot-caption {
    font-size: 12px;
    color: var(--text-3);
    margin-top: 8px;
  }

  /* ---- Bar Chart ---- */
  .bars-section {
    max-width: var(--max-w);
    margin: 100px auto 0;
    padding: 0 24px;
  }
  .bars-section .lead {
    font-size: 24px;
    font-weight: 600;
    letter-spacing: -0.02em;
    line-height: 1.5;
    margin-bottom: 8px;
  }
  .bars-section .lead .accent { color: var(--accent); font-weight: 700; }
  .bars-section .hint {
    font-size: 13px;
    color: var(--text-3);
    margin-bottom: 32px;
  }
  .bar-row {
    cursor: pointer;
    padding: 10px 0;
    border-bottom: 1px solid #EEECEB;
    transition: background 150ms;
  }
  .bar-row:hover { background: #F5F5F4; margin: 0 -12px; padding: 10px 12px; border-radius: 6px; border-color: transparent; }
  .bar-row.top3 .bar-name { font-weight: 700; }
  .bar-label-row {
    display: flex;
    justify-content: space-between;
    align-items: baseline;
    margin-bottom: 6px;
  }
  .bar-name { font-size: 14px; font-weight: 500; }
  .bar-meta { font-size: 12px; color: var(--text-3); }
  .bar-track {
    height: 20px;
    background: #F5F5F4;
    border-radius: 4px;
    overflow: hidden;
  }
  .bar-fill {
    height: 100%;
    background: var(--accent);
    border-radius: 4px;
    display: flex;
    align-items: center;
    justify-content: flex-end;
    padding-right: 8px;
    min-width: 32px;
  }
  .bar-score {
    font-size: 11px;
    font-weight: 700;
    color: white;
  }
  .bar-quotes-panel {
    padding: 12px 0 12px 16px;
    border-left: 2px solid var(--accent);
    margin: 0 0 8px 0;
  }
  .bar-quote {
    font-size: 13px;
    color: var(--text-2);
    font-style: italic;
    line-height: 1.6;
    margin-bottom: 8px;
  }
  .bar-quote:last-child { margin-bottom: 0; }
  .bar-quote mark { background: var(--accent-light); color: var(--accent); font-style: normal; padding: 1px 3px; border-radius: 2px; }

  /* ---- Deep Dives ---- */
  .deepdive { margin-top: 100px; }
  .dd-label {
    font-size: 12px;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 1.5px;
    color: var(--accent);
    margin-bottom: 8px;
  }
  .dd-title {
    font-size: 28px;
    font-weight: 700;
    letter-spacing: -0.03em;
    margin-bottom: 8px;
  }
  .dd-meta {
    font-size: 13px;
    color: var(--text-3);
    margin-bottom: 36px;
  }
  .dd-subtitle {
    font-size: 16px;
    font-weight: 600;
    color: var(--text-2);
    margin-bottom: 24px;
  }
  .dd-analysis {
    margin-top: 32px;
  }
  .dd-analysis h3 {
    font-size: 13px;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 0.5px;
    color: var(--text-2);
    margin-bottom: 8px;
  }
  .dd-analysis p {
    font-size: 15px;
    color: var(--text);
    line-height: 1.7;
  }
  .dd-punchline {
    font-size: 20px;
    font-weight: 600;
    font-style: italic;
    color: var(--accent);
    margin: 36px 0;
    padding-left: 20px;
    border-left: 3px solid var(--accent);
    line-height: 1.5;
  }

  /* DD1: Big Quotes */
  .dd1-quotes { display: flex; flex-direction: column; gap: 16px; }
  .big-quote {
    font-size: 18px;
    line-height: 1.6;
    color: var(--text);
    padding: 20px 24px;
    background: #F5F5F4;
    border-radius: 8px;
    border: none;
    font-style: italic;
  }
  .big-quote mark { background: var(--accent-light); color: var(--accent); font-style: normal; padding: 2px 4px; border-radius: 3px; }

  /* DD2: Journey Timeline */
  .journey {
    display: flex;
    align-items: center;
    gap: 0;
    overflow-x: auto;
    padding: 20px 0;
    margin-bottom: 24px;
  }
  .journey-step {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 8px;
    flex-shrink: 0;
    font-size: 13px;
    font-weight: 500;
    color: var(--text);
  }
  .journey-dot {
    width: 12px;
    height: 12px;
    border-radius: 50%;
    background: var(--text);
  }
  .journey-step.break { color: var(--accent); font-weight: 700; }
  .journey-step.break .journey-dot { background: var(--accent); width: 16px; height: 16px; box-shadow: 0 0 0 4px var(--accent-light); }
  .journey-step.faded { opacity: 0.25; }
  .journey-line {
    width: 40px;
    height: 2px;
    background: var(--border);
    flex-shrink: 0;
  }
  .journey-line.faded { background: var(--border); opacity: 0.3; stroke-dasharray: 4 4; }
  .speech-bubble {
    font-size: 14px;
    font-style: italic;
    color: var(--text-2);
    padding: 12px 16px;
    background: #F5F5F4;
    border-radius: 8px;
    margin-bottom: 10px;
    position: relative;
  }
  .speech-bubble mark { background: var(--accent-light); color: var(--accent); font-style: normal; padding: 1px 3px; border-radius: 2px; }

  /* DD3: Before/After */
  .comparison {
    display: grid;
    grid-template-columns: 1fr 1px 1fr;
    gap: 32px;
    margin-bottom: 20px;
  }
  .comp-divider { background: var(--border); }
  .comp-col h4 {
    font-size: 12px;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 1px;
    color: var(--text-3);
    margin-bottom: 16px;
  }
  .comp-col.expect p { font-size: 15px; line-height: 1.7; color: var(--text); }
  .comp-col.got blockquote {
    font-size: 14px;
    font-style: italic;
    color: var(--text-2);
    line-height: 1.6;
    padding: 10px 14px;
    background: var(--accent-light);
    border-radius: 6px;
    border: none;
    margin-bottom: 10px;
  }
  .comp-col.got blockquote mark { background: transparent; color: var(--accent); font-weight: 600; }

  /* ---- Actions ---- */
  .dd-actions { margin-top: 32px; }
  .dd-actions h3 {
    font-size: 13px;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 0.5px;
    color: var(--text-2);
    margin-bottom: 16px;
  }
  .action-row {
    display: flex;
    gap: 16px;
    padding: 10px 0;
    border-bottom: 1px solid #EEECEB;
    font-size: 14px;
    line-height: 1.6;
  }
  .action-row:last-child { border-bottom: none; }
  .action-level {
    flex-shrink: 0;
    width: 80px;
    font-size: 12px;
    font-weight: 700;
    color: var(--text-3);
    padding-top: 2px;
  }
  .action-text { color: var(--text); }

  .dd-test {
    margin-top: 24px;
    padding: 16px 20px;
    background: var(--accent-light);
    border-radius: 8px;
    font-size: 14px;
    line-height: 1.6;
    color: var(--text);
  }
  .dd-test strong { color: var(--accent); }

  /* ---- Experiments (detailed cards) ---- */
  .exp-cards { display: flex; flex-direction: column; gap: 24px; }
  .exp-card {
    border: 1px solid var(--border);
    border-radius: 10px;
    overflow: hidden;
    background: var(--surface);
  }
  .exp-header {
    padding: 20px 24px;
    border-bottom: 1px solid #EEECEB;
  }
  .exp-priority {
    display: inline-block;
    font-size: 11px;
    font-weight: 700;
    letter-spacing: 0.5px;
    color: var(--accent);
    background: var(--accent-light);
    padding: 3px 10px;
    border-radius: 4px;
    margin-bottom: 10px;
  }
  .exp-hypothesis {
    font-size: 16px;
    font-weight: 600;
    font-style: italic;
    line-height: 1.5;
    color: var(--text);
  }
  .exp-body { padding: 20px 24px; }
  .exp-field { margin-bottom: 16px; }
  .exp-field:last-child { margin-bottom: 0; }
  .exp-label {
    display: block;
    font-size: 11px;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 0.5px;
    color: var(--text-3);
    margin-bottom: 4px;
  }
  .exp-field p { font-size: 14px; line-height: 1.6; color: var(--text); }
  .exp-grid {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 16px;
    margin-bottom: 16px;
  }
  .exp-field.expected {
    padding: 14px 18px;
    background: #F5F5F4;
    border-radius: 8px;
  }
  .exp-field.prereq {
    padding: 14px 18px;
    background: #FFFBEB;
    border-radius: 8px;
    border: 1px solid #FDE68A;
  }

  /* Fallback table */
  .exp-table { width: 100%; border-collapse: collapse; }
  .exp-table th { text-align: left; padding: 10px 0; font-size: 12px; font-weight: 700; color: var(--text-3); text-transform: uppercase; letter-spacing: 0.5px; border-bottom: 2px solid var(--border); }
  .exp-table td { padding: 14px 14px 14px 0; font-size: 14px; border-bottom: 1px solid #EEECEB; line-height: 1.5; }

  /* ---- CTA ---- */
  .cta-section { border-top: 1px solid var(--border); padding-top: 48px; }
  .cta-title {
    font-size: 22px;
    font-weight: 700;
    letter-spacing: -0.02em;
    margin-bottom: 20px;
  }
  .cta-section p {
    font-size: 15px;
    line-height: 1.8;
    color: var(--text-2);
    margin-bottom: 12px;
  }
  .cta-section em { font-style: normal; font-weight: 600; color: var(--text); }
  .cta-section strong { color: var(--text); }
  .cta-closer {
    padding: 16px 20px;
    background: #F5F5F4;
    border-radius: 8px;
    border-left: 3px solid var(--accent);
    margin-top: 8px;
  }
  .cta-link {
    display: inline-block;
    margin-top: 16px;
    font-size: 15px;
    font-weight: 600;
    color: var(--accent);
    text-decoration: none;
    border-bottom: 1px solid var(--accent);
    padding-bottom: 2px;
    transition: opacity 150ms;
  }
  .cta-link:hover { opacity: 0.7; }

  /* Waitlist offer */
  .waitlist-box {
    margin-top: 28px;
    padding: 28px 28px 24px;
    background: var(--surface);
    border: 1.5px solid var(--text);
    border-radius: 10px;
  }
  .waitlist-label {
    font-size: 11px;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 1.5px;
    color: var(--text-3);
    margin-bottom: 14px;
  }
  .waitlist-box p {
    font-size: 15px;
    line-height: 1.7;
    color: var(--text);
    margin-bottom: 10px;
  }
  .waitlist-box strong { color: var(--text); }
  .waitlist-fine {
    font-size: 13px !important;
    color: var(--text-3) !important;
    margin-bottom: 18px !important;
  }
  .waitlist-btn {
    display: inline-block;
    padding: 12px 32px;
    background: var(--text);
    color: var(--bg);
    font-size: 15px;
    font-weight: 600;
    text-decoration: none;
    border-radius: 6px;
    transition: opacity 150ms;
  }
  .waitlist-btn:hover { opacity: 0.85; }

  /* ---- Connect (LinkedIn) ---- */
  .connect-section {
    text-align: center;
    padding-top: 48px;
    padding-bottom: 48px;
    border-top: 1px solid var(--border);
  }
  .connect-section p {
    font-size: 15px;
    color: var(--text-2);
    margin-bottom: 12px;
  }
  .linkedin-link {
    display: inline-block;
    font-size: 15px;
    font-weight: 600;
    color: var(--text);
    text-decoration: none;
    padding: 10px 28px;
    border: 1.5px solid var(--text);
    border-radius: 6px;
    transition: background 150ms, color 150ms;
  }
  .linkedin-link:hover {
    background: var(--text);
    color: var(--bg);
  }

  /* ---- Footer ---- */
  .footer {
    max-width: var(--max-w);
    margin: 80px auto 0;
    padding: 24px;
    text-align: center;
    font-size: 12px;
    color: var(--text-3);
    border-top: 1px solid var(--border);
  }

  /* ---- Responsive ---- */
  @media (max-width: 680px) {
    .intro { padding-top: 80px; }
    .intro h1 { font-size: 28px; }
    .dd-title { font-size: 22px; }
    .comparison { grid-template-columns: 1fr; gap: 24px; }
    .comp-divider { display: none; }
    .comp-col.got { border-top: 1px solid var(--border); padding-top: 20px; }
    .journey { flex-wrap: wrap; gap: 8px; }
    .journey-line { width: 20px; }
    .exp-grid { grid-template-columns: 1fr; }
    .section + .section { margin-top: 72px; }
  }

  @media print {
    .methodology, .cta-section, .connect-section { display: none; }
    .section + .section { margin-top: 40px; }
    body { background: white; }
  }
</style>
</head>
<body>

  <!-- Intro -->
  <div class="intro">
    <h1>${t.introLine(analysis.app.name, analysis.totalReviews)}</h1>
    <div class="app-meta">${esc(analysis.app.category)} · ${esc(analysis.app.model)} · ${new Date().toLocaleDateString(lang === 'ko' ? 'ko-KR' : 'en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</div>
    <p class="summary">${esc(analysis.executiveSummary)}</p>
    ${methodologyHTML()}
  </div>

  <!-- Dot Visualization -->
  <div class="dot-section">
    <p class="lead">${t.signalLine(signalRate, analysis.subscriptionRelated)}</p>
    <div class="dot-grid">${dotGrid()}</div>
    <p class="dot-caption">${t.dotCaption}</p>
  </div>

  <!-- Bar Chart -->
  <div class="bars-section">
    <p class="lead">${t.patternLine(sorted.length)}</p>
    <p class="hint">${t.patternHint}</p>
    ${barChart()}
  </div>

  <!-- Deep Dive Intro -->
  <div class="section" style="margin-top:100px">
    <p class="lead" style="font-size:20px;font-weight:600;letter-spacing:-0.02em">${t.deepdiveIntro}</p>
  </div>

  <!-- Deep Dives (3 different layouts) -->
  ${top3[0] ? deepDive1(top3[0], 0) : ''}
  ${top3[1] ? deepDive2(top3[1], 1) : ''}
  ${top3[2] ? deepDive3(top3[2], 2) : ''}

  <!-- Experiments -->
  ${experimentsHTML()}

  <!-- CTA -->
  ${ctaHTML()}

  <!-- LinkedIn -->
  ${linkedinHTML()}

  <!-- Footer -->
  <div class="footer">${t.footer}</div>

<script>
// Count-up animation for intro number
function countUp(el, target, duration) {
  let start = null;
  function step(ts) {
    if (!start) start = ts;
    const p = Math.min((ts - start) / duration, 1);
    el.textContent = Math.floor(p * target);
    if (p < 1) requestAnimationFrame(step);
  }
  requestAnimationFrame(step);
}

// Observe intro number
const numEl = document.querySelector('.num');
if (numEl) {
  const target = parseInt(numEl.dataset.target, 10);
  const observer = new IntersectionObserver((entries) => {
    entries.forEach(e => {
      if (e.isIntersecting) {
        countUp(numEl, target, 800);
        observer.disconnect();
      }
    });
  }, { threshold: 0.5 });
  observer.observe(numEl);
}

// Bar chart toggle
function toggleQuotes(barRow) {
  const panel = barRow.nextElementSibling;
  if (panel && panel.classList.contains('bar-quotes-panel')) {
    panel.style.display = panel.style.display === 'none' ? 'block' : 'none';
  }
}
</script>

</body>
</html>`;

fs.writeFileSync(path.resolve(outputFile), html);
console.log(`Report generated: ${path.resolve(outputFile)}`);
